"""
Unified Knowledge Base Builder
Populates 5 ChromaDB collections from structured JSON data
"""
import json
import os
import chromadb
from pathlib import Path

os.environ["TRANSFORMERS_OFFLINE"] = "1"
os.environ["HF_DATASETS_OFFLINE"] = "1"

from sentence_transformers import SentenceTransformer

KB_DIR    = Path("kb/unified_kb")
CHROMA_DIR = Path("kb/chroma_unified")

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
client = chromadb.PersistentClient(path=str(CHROMA_DIR))

COLLECTIONS = [
    "sc_rules",        # Smart Contract Rules
    "audit_findings",  # Audit Findings
    "network_incidents", # Network Incidents
    "validator_baselines", # Validator Baselines
    "research_knowledge",  # Research Knowledge
]


def embed(text: str):
    return embedding_model.encode(text).tolist()


def load_collection(name: str):
    try:
        client.delete_collection(name)
    except Exception:
        pass
    return client.create_collection(name)


def ingest(collection, records: list, id_prefix: str):
    for i, record in enumerate(records):
        content = record.get("content", json.dumps(record))
        metadata = {k: str(v) for k, v in record.items() if k != "content"}
        collection.add(
            ids=[f"{id_prefix}_{i:04d}"],
            embeddings=[embed(content)],
            documents=[content],
            metadatas=[metadata]
        )
    print(f"  ✅ Ingested {len(records)} records into {collection.name}")


# ── COLLECTION 1: SMART CONTRACT RULES ──────────────────────
SC_RULES = [
    # VRust 8 types
    {"rule_id":"SC-001","name":"Missing Signer Check","source":"VRust","category":"authentication","severity":"critical","pattern":"AccountInfo without is_signer check","fix":"Use Signer<'info> or verify is_signer","content":"Missing signer check: Account can be passed without requiring signature. Use Signer<'info> in Accounts struct instead of AccountInfo<'info>. Without this any pubkey can be passed as the authority."},
    {"rule_id":"SC-002","name":"Missing Ownership Check","source":"VRust","category":"authorization","severity":"critical","pattern":"No program ownership verification on account","fix":"Verify account.owner == program_id","content":"Missing ownership check: Program does not verify it owns the account before modifying it. An attacker can pass a fake account owned by a different program. Always check account.owner == program_id or use Anchor Account<> wrapper which does this automatically."},
    {"rule_id":"SC-003","name":"Integer Overflow","source":"VRust","category":"arithmetic","severity":"high","pattern":"Addition without checked_add","fix":"Use checked_add().ok_or(error)?","content":"Integer overflow: Rust integers wrap in release mode. Use checked_add() instead of += to prevent balance from wrapping to 0. Example: balance = balance.checked_add(amount).ok_or(error!(ErrorCode::Overflow))?"},
    {"rule_id":"SC-004","name":"Integer Underflow","source":"VRust","category":"arithmetic","severity":"critical","pattern":"Subtraction without checked_sub","fix":"Use checked_sub().ok_or(error)? or require balance >= amount","content":"Integer underflow: Subtracting more than the current balance wraps to u64::MAX in release mode. Use checked_sub() or add require!(balance >= amount) before subtraction."},
    {"rule_id":"SC-005","name":"Type Confusion","source":"VRust","category":"type-safety","severity":"high","pattern":"Account deserialized without discriminator check","fix":"Use Anchor Account<'info, T> wrapper","content":"Type confusion: Account can be deserialized as wrong type. Anchor Account<'info, T> automatically checks the 8-byte discriminator. Without it an attacker can pass an account of different type that passes all other checks."},
    {"rule_id":"SC-006","name":"PDA Bump Not Canonical","source":"VRust","category":"pda","severity":"high","pattern":"create_program_address with user-supplied bump","fix":"Use find_program_address and store canonical bump","content":"Non-canonical PDA bump: Using create_program_address with a user-supplied bump allows an attacker to use a non-canonical bump to derive a different valid PDA. Always use find_program_address which returns the canonical bump, then store it in the account for future verification."},
    {"rule_id":"SC-007","name":"Account Data Matching Failure","source":"VRust","category":"authorization","severity":"critical","pattern":"Stored admin != signer with no check","fix":"Add constraint = config.admin == signer.key()","content":"Account data matching failure: Program stores an admin pubkey but does not verify the signer matches it. Use Anchor constraint: #[account(constraint = config.admin == admin.key())] or add require!(ctx.accounts.admin.key() == config.admin)"},
    {"rule_id":"SC-008","name":"Insecure Account Reallocation","source":"VRust","category":"memory","severity":"medium","pattern":"realloc without zero_init after size reduction","fix":"Set zero_init=true when increasing after reducing","content":"Insecure account reallocation: When an account is first reduced then increased in size, old data may be exposed. Use zero_init=true to clear memory after any size reduction."},
    # Sealevel 21 types
    {"rule_id":"SC-009","name":"Account Data Matching","source":"Sealevel-Attacks","category":"authorization","severity":"critical","pattern":"Admin action without verifying stored admin matches signer","fix":"constraint = config_data.admin == admin.key()","content":"Account data matching: Must verify stored data matches the signer. Add Anchor constraint: #[account(mut, constraint = config_data.admin == admin.key())] or explicitly check require_keys_eq!(admin.key(), config.admin)"},
    {"rule_id":"SC-010","name":"Account Reloading After CPI","source":"Sealevel-Attacks","category":"cpi","severity":"high","pattern":"Using stale account data after CPI call","fix":"Call ctx.accounts.account.reload()? after CPI","content":"Account reloading: Anchor does not refresh account state after a CPI. If another program modifies an account during CPI, your program will use stale data. Always call reload() after any CPI that might modify shared accounts."},
    {"rule_id":"SC-011","name":"Arbitrary CPI","source":"Sealevel-Attacks","category":"cpi","severity":"critical","pattern":"invoke() without verifying target program ID","fix":"Check program.key() == expected_program::ID before invoke","content":"Arbitrary CPI: If a program allows arbitrary CPIs without verifying the target program identity, an attacker can redirect the call to a malicious program. Always verify: require!(ctx.accounts.program.key() == &expected_program::ID)"},
    {"rule_id":"SC-012","name":"Duplicate Mutable Accounts","source":"Sealevel-Attacks","category":"logic","severity":"high","pattern":"Same account passed twice as mutable","fix":"Add constraint = acct1.key() != acct2.key()","content":"Duplicate mutable accounts: An attacker can pass the same account twice when two different mutable accounts are expected. Add Anchor constraint: #[account(mut, constraint = reward_account.key() != bonus_account.key())]"},
    {"rule_id":"SC-013","name":"Initialization Frontrunning","source":"Sealevel-Attacks","category":"initialization","severity":"critical","pattern":"Initialize function callable by anyone","fix":"Check upgrade_authority == signer before init","content":"Initialization frontrunning: If initialize() can be called by anyone, an attacker can frontrun the deployment transaction and take control. Verify: #[account(constraint = program_data.upgrade_authority_address == Some(authority.key()))]"},
    {"rule_id":"SC-014","name":"PDA Sharing","source":"Sealevel-Attacks","category":"pda","severity":"high","pattern":"Same PDA seeds used for different authority domains","fix":"Use distinct seed prefixes per domain","content":"PDA sharing: Using the same seed for PDAs across different functionalities allows unauthorized cross-domain access. Use unique prefixes: seeds=[b'staking_pool', pool.key()] vs seeds=[b'rewards_pool', pool.key()]"},
    {"rule_id":"SC-015","name":"Closing Accounts Insecurely","source":"Sealevel-Attacks","category":"account-lifecycle","severity":"high","pattern":"Transfer lamports without setting CLOSED discriminator","fix":"Set CLOSED_ACCOUNT_DISCRIMINATOR and zero data","content":"Insecure account closure: Just transferring lamports does not prevent account reuse. Must set CLOSED_ACCOUNT_DISCRIMINATOR in the first 8 bytes and zero all data to prevent revival attacks."},
    {"rule_id":"SC-016","name":"Revival Attack","source":"Sealevel-Attacks","category":"account-lifecycle","severity":"high","pattern":"Closed account can be reinitialized","fix":"Check discriminator is not CLOSED before init","content":"Revival attack: A closed account can be revived by re-funding it and reinitializing before the transaction ends. Guard initialization with: require!(account.discriminator != CLOSED_ACCOUNT_DISCRIMINATOR)"},
    {"rule_id":"SC-017","name":"Authority Transfer Missing","source":"Sealevel-Attacks","category":"governance","severity":"medium","pattern":"No mechanism to transfer admin authority","fix":"Implement two-step nominate + accept pattern","content":"Missing authority transfer: Programs need a secure way to transfer admin keys. Implement two-step: nominate_new_authority() stores pending, accept_authority() confirms. This prevents accidental or malicious transfers."},
    {"rule_id":"SC-018","name":"Frontrunning","source":"Sealevel-Attacks","category":"mev","severity":"high","pattern":"Price or state changeable between user submission and execution","fix":"Include expected_price in purchase transaction","content":"Frontrunning: A seller can change the price between when a buyer submits and when transaction executes. Include expected_price parameter and verify: require!(listing.price == expected_price, PriceMismatch)"},
    {"rule_id":"SC-019","name":"Loss of Precision","source":"Sealevel-Attacks","category":"arithmetic","severity":"medium","pattern":"Division before multiplication causes rounding loss","fix":"Multiply before dividing, use floor not round","content":"Loss of precision: Dividing before multiplying causes rounding errors. Always: result = (a * b) / c not (a / c) * b. Use try_floor_u64() instead of try_round_u64() to avoid artificial inflation."},
    {"rule_id":"SC-020","name":"Remaining Accounts Not Validated","source":"Sealevel-Attacks","category":"input-validation","severity":"high","pattern":"ctx.remaining_accounts used without ownership check","fix":"Verify owner and structure of each remaining account","content":"Unvalidated remaining accounts: ctx.remaining_accounts bypasses Anchor validation. Must manually verify: for account in ctx.remaining_accounts { require!(account.owner == EXPECTED_PROGRAM) }"},
    {"rule_id":"SC-021","name":"Unsafe Rust Usage","source":"Sealevel-Attacks","category":"memory-safety","severity":"high","pattern":"unsafe block with raw pointer dereference","fix":"Minimize unsafe, encapsulate in safe abstractions","content":"Unsafe Rust: The unsafe keyword bypasses memory safety. In Solana programs this can cause memory corruption and information leakage. Minimize use, document thoroughly, and audit unsafe blocks regularly."},
    {"rule_id":"SC-022","name":"Panic in Program","source":"Sealevel-Attacks","category":"error-handling","severity":"medium","pattern":"unwrap() or expect() calls that can panic","fix":"Use Result and ? operator instead of unwrap()","content":"Program panic: Rust panics in Solana programs cause transaction failure with cryptic errors. Replace unwrap() with ? operator and use custom error codes for all failure paths."},
    {"rule_id":"SC-023","name":"Seed Collision","source":"Sealevel-Attacks","category":"pda","severity":"high","pattern":"Two different inputs derive same PDA","fix":"Use unique prefixes and user IDs in seeds","content":"Seed collision: If two different seed combinations produce the same PDA, state can be corrupted or funds stolen. Use unique prefixes (b'user_stake', user_id) and include timestamps or unique identifiers."},
    {"rule_id":"SC-024","name":"Type Cosplay","source":"Sealevel-Attacks","category":"type-safety","severity":"critical","pattern":"Account deserialized as wrong type","fix":"Use Anchor Account<'info, T> for automatic discriminator check","content":"Type cosplay: An attacker passes an account of type A when type B is expected. Anchor Account<'info, T> checks the 8-byte discriminator automatically. Without it, any account with the right size passes."},
    {"rule_id":"SC-025","name":"Casting Vulnerability","source":"Sealevel-Attacks","category":"arithmetic","severity":"high","pattern":"as keyword used for integer type conversion","fix":"Use u32::try_from(amount).map_err(|_| ProgramError::InvalidArgument)","content":"Casting vulnerability: The as keyword truncates values silently. Casting u64 to u32 where value > 4294967295 wraps without error. Use try_from() which returns Err on overflow."},
    # Neodyme pitfalls
    {"rule_id":"SC-026","name":"Missing Freeze Authority Check","source":"Neodyme","category":"token","severity":"high","pattern":"Token account used without checking freeze authority","fix":"Verify freeze authority is None or expected","content":"Missing freeze authority: Token accounts can be frozen by their freeze authority. A program that does not check this may try to transfer from a frozen account, causing unexpected failures or being exploited by a malicious token issuer who freezes accounts selectively."},
    {"rule_id":"SC-027","name":"SPL Token Owner Mismatch","source":"Neodyme","category":"token","severity":"critical","pattern":"Token account owner not verified against expected program","fix":"Check token_account.owner == token_program","content":"SPL token owner mismatch: Token accounts must be owned by the SPL Token program. A fake token account owned by an attacker-controlled program can pass balance checks while allowing unauthorized transfers."},
    {"rule_id":"SC-028","name":"Writable Account Not Required","source":"Neodyme","category":"account-validation","severity":"medium","pattern":"Account marked writable but no mutation check","fix":"Only mark accounts writable when they will be modified","content":"Unnecessary writable accounts: Marking accounts writable unnecessarily increases attack surface and wastes compute. More critically, forgetting to mark an account writable when it should be causes runtime failures. Be explicit about which accounts are modified."},
]

# ── COLLECTION 2: AUDIT FINDINGS ────────────────────────────
AUDIT_FINDINGS = [
    {"source":"Neodyme","project":"Jet Protocol","vulnerability":"Missing ownership check on reserve account","impact":"Unauthorized fund access","severity":"critical","fix":"Verify reserve.owner == jet_program_id","content":"Neodyme audit finding - Jet Protocol: Reserve accounts were not verified to be owned by the Jet program. An attacker could substitute a fake reserve account to manipulate interest calculations and extract funds."},
    {"source":"Neodyme","project":"Mango Markets","vulnerability":"Oracle price manipulation","impact":"$114M exploit","severity":"critical","fix":"Use TWAP oracle with staleness check","content":"Neodyme audit finding - Mango Markets: Oracle prices were manipulable within a single transaction. Attacker inflated collateral value via market manipulation, took out loans, then abandoned the position after draining the treasury."},
    {"source":"Neodyme","project":"Wormhole","vulnerability":"Missing signature verification on guardian set","impact":"$320M exploit","severity":"critical","fix":"Verify all guardian signatures on-chain","content":"Neodyme/Certik audit - Wormhole: A deprecated instruction verify_signatures stored signature results but the actual verification was skipped due to a code path that was not removed. Attacker minted 120,000 wETH without bridging any assets."},
    {"source":"Neodyme","project":"Cashio","vulnerability":"Missing account ownership validation on collateral","impact":"$48M exploit","severity":"critical","fix":"Verify collateral account owner chain","content":"Cashio exploit: CASH stablecoin allowed minting backed by any SPL token account that passed superficial checks. Missing ownership verification in the collateral account chain allowed attacker to mint unbacked CASH."},
    {"source":"OtterSec","project":"Serum DEX","vulnerability":"PDA authority not verified","impact":"Unauthorized order cancellation","severity":"high","fix":"Add has_one constraint on market authority PDA","content":"OtterSec audit - Serum: Market authority PDA was derived but not verified against the stored authority in the market account. Any account with a valid PDA derivation could cancel orders on any market."},
    {"source":"OtterSec","project":"Solend","vulnerability":"Flash loan callback reentrancy","impact":"Potential fund drain via reentrancy","severity":"critical","fix":"Add reentrancy guard, check state before CPI","content":"OtterSec audit - Solend: Flash loan callback mechanism did not guard against reentrancy. During the callback the contract state was inconsistent, allowing an attacker to recursively call the loan function."},
    {"source":"OtterSec","project":"Marinade Finance","vulnerability":"Stake account not validated before delegation","impact":"Loss of staking rewards","severity":"medium","fix":"Verify stake account state before activating","content":"OtterSec audit - Marinade Finance: Stake accounts were not validated to be in the correct state before delegation. Passing a deactivating stake account caused the delegation to fail silently, losing the staking period."},
    {"source":"Trail of Bits","project":"SPL Token","vulnerability":"Missing check on mint authority","impact":"Unauthorized token minting","severity":"critical","fix":"Verify mint.mint_authority == Some(expected_authority)","content":"Trail of Bits audit - SPL Token: Several programs using SPL tokens did not verify the mint authority before performing operations that depended on controlled supply. An attacker with any mint authority could inflate supply."},
    {"source":"Sec3","project":"Anchor Program","vulnerability":"Two SPL token account caveats","impact":"Token account reuse across pools","severity":"high","fix":"Use unique seeds per pool for token PDAs","content":"Sec3 blog - SPL token caveats: Programs that derive token account PDAs with shared seeds allow the same token account to be used across different pools. This breaks accounting isolation and can be exploited to drain funds from one pool using state from another."},
    {"source":"Immunefi","project":"Multiple Solana Programs","vulnerability":"Missing initialized account check","impact":"Reinitialization attack","severity":"critical","fix":"Check account discriminator is zero before init","content":"Immunefi bounty pattern - Reinitialization: Programs that allow initialize() to be called on already-initialized accounts allow attackers to reset admin authority. Check that the account discriminator is all zeros before accepting initialization."},
    {"source":"CVE","project":"Solana Validator","vulnerability":"CVE-2022-31267 - gossip amplification","impact":"Network DDoS","severity":"high","fix":"Rate limit gossip messages per IP","content":"CVE-2022-31267: Solana validator gossip protocol could be exploited for DDoS amplification. Gossip messages were forwarded without rate limiting per sender IP, allowing a small number of packets to generate large amplified floods."},
    {"source":"CVE","project":"Solana Labs","vulnerability":"CVE-2023-27046 - transaction ordering manipulation","impact":"MEV extraction","severity":"medium","fix":"Implement fair transaction ordering","content":"CVE-2023-27046: Transaction ordering in Solana leader slots could be manipulated for MEV extraction. Validators could reorder transactions to front-run user trades without detection."},
]

# ── COLLECTION 3: NETWORK INCIDENTS ─────────────────────────
NETWORK_INCIDENTS = [
    {"id":"SOL-2021-001","date":"2021-09-14","type":"outage","cause":"transaction_flood","duration_hours":17,"impact":"Network halt","description":"September 2021 outage: A Grape Protocol IDO triggered a flood of 400,000 transactions per second. The network ran out of memory processing the flood and validators crashed. Required coordinated restart.","content":"Solana September 2021 outage: 17-hour network halt caused by transaction flood from Grape Protocol IDO. 400k TPS overwhelmed validator memory. Root cause: no backpressure mechanism for transaction ingestion. Fixed by QUIC implementation."},
    {"id":"SOL-2022-001","date":"2022-01-12","type":"spam_attack","cause":"candy_machine_nft_mint","duration_hours":8,"impact":"Network degradation","description":"January 2022: NFT candy machine bots flooded the network with failed mint transactions consuming 25% of block capacity.","content":"Solana January 2022 NFT spam attack: Candy machine NFT mints generated massive bot traffic. Bots sent thousands of failed transactions per second trying to win mint slots. Network degraded significantly. Led to fee market discussions."},
    {"id":"SOL-2022-002","date":"2022-05-01","type":"outage","cause":"duplicate_block_bug","duration_hours":7,"impact":"Network halt","description":"May 2022: A duplicate block issue caused validators to get stuck processing conflicting forks. Required coordinated restart.","content":"Solana May 2022 outage: Duplicate block production by a malicious or buggy validator caused consensus failure. Validators could not agree on canonical chain state. 7-hour downtime. Fixed by improving fork detection logic."},
    {"id":"SOL-2022-003","date":"2022-06-01","type":"outage","cause":"memory_exhaustion","duration_hours":4.5,"impact":"Network halt","description":"June 2022: Network halt due to non-deterministic behavior in a validator component causing memory exhaustion.","content":"Solana June 2022 outage: Memory exhaustion in validator from non-deterministic transaction processing. Validators ran out of heap memory processing certain transaction sequences. Required patch and coordinated restart."},
    {"id":"SOL-2022-004","date":"2022-09-30","type":"validator_bug","cause":"quic_implementation","duration_hours":0,"impact":"Degraded performance","description":"QUIC implementation bug causing packet loss under high load. Fixed in v1.14.","content":"Solana QUIC bug 2022: The new QUIC-based transaction ingestion had a bug causing packet drops under high load. TPU (Transaction Processing Unit) dropped valid transactions. Fixed by improving QUIC congestion control parameters."},
    {"id":"SOL-2023-001","date":"2023-02-25","type":"outage","cause":"consensus_bug","duration_hours":19,"impact":"Network halt","description":"February 2023: A consensus bug caused the network to halt for 19 hours. One of the longest outages.","content":"Solana February 2023 outage: 19-hour network halt caused by a bug in the consensus mechanism when processing blocks with certain transaction patterns. Required emergency patch deployment across all validators."},
    {"id":"SOL-2024-001","date":"2024-02-06","type":"network_congestion","cause":"memecoin_trading","duration_hours":48,"impact":"High failure rate","description":"February 2024: Memecoin trading frenzy caused 75% transaction failure rate for normal users.","content":"Solana February 2024 congestion: Memecoin trading on pump.fun and Raydium generated extreme transaction volume. Normal transactions failed at 75% rate. Led to implementation of priority fees and QUIC improvements. Nakamoto coefficient dropped as major validators handled disproportionate load."},
    {"id":"SOL-2024-002","date":"2024-04-18","type":"network_congestion","cause":"nft_and_defi_volume","duration_hours":72,"impact":"Severe degradation","description":"April 2024: Second major congestion event in 2024 with 75%+ failure rate for non-priority transactions.","content":"Solana April 2024 congestion: Second major congestion event. Combined NFT, DeFi, and memecoin volume overwhelmed the network. Priority fee market functioned but base-fee transactions nearly unusable. Motivated SIMD-0096 local fee market proposal."},
    {"id":"SOL-WORMHOLE-2022","date":"2022-02-02","type":"bridge_exploit","cause":"missing_signature_verification","amount_lost_usd":320000000,"impact":"$320M stolen","description":"Wormhole bridge exploit: deprecated verify_signatures instruction allowed minting without real guardian signatures.","content":"Wormhole bridge exploit February 2022: $320M stolen. A deprecated instruction allowed the attacker to spoof guardian signature verification. The verify_signatures instruction stored results without actually verifying. Attacker minted 120,000 wETH without depositing ETH."},
    {"id":"SOL-MANGO-2022","date":"2022-10-11","type":"defi_exploit","cause":"oracle_manipulation","amount_lost_usd":114000000,"impact":"$114M drained","description":"Mango Markets oracle price manipulation via market manipulation within single transaction.","content":"Mango Markets exploit October 2022: $114M stolen. Attacker used $10M to buy MNGO perpetuals, drove price up 10x via spot market manipulation in same transaction, used inflated collateral to borrow all available funds from treasury. Oracle used spot price without TWAP."},
    {"id":"SOL-CASHIO-2022","date":"2022-03-23","type":"defi_exploit","cause":"missing_ownership_check","amount_lost_usd":48000000,"impact":"$48M stolen","description":"Cashio stablecoin exploit: unbounded minting via missing collateral ownership verification.","content":"Cashio exploit March 2022: $48M stolen. CASH stablecoin collateral verification had missing ownership checks in the account chain. Attacker provided fake accounts at each level of the check, passing all validations while providing no real collateral. Minted unlimited CASH."},
]

# ── COLLECTION 4: VALIDATOR BASELINES ───────────────────────
VALIDATOR_BASELINES = [
    {"metric":"tps_average","normal_range":"2000-4000","alert_threshold":"< 1000","unit":"transactions/second","source":"Helius","content":"Solana TPS baseline: Normal network throughput is 2000-4000 TPS. Drops below 1000 TPS indicate severe congestion or network issues. Historical peak is ~65000 TPS theoretical, ~4000 TPS practical with real transactions."},
    {"metric":"skip_rate","normal_range":"0.5-2%","alert_threshold":"> 5%","unit":"percentage","source":"Validators.app","content":"Validator skip rate: Normal skip rate is 0.5-2%. A skip means the validator failed to produce a block in their assigned slot. Skip rate above 5% indicates validator performance issues. Above 10% may indicate network attack or validator hardware problems."},
    {"metric":"nakamoto_coefficient","normal_range":"19-22","alert_threshold":"< 15","unit":"count","source":"Research","content":"Nakamoto coefficient: Measures decentralization — minimum validators to control 33% of stake. Normal range 19-22 for Solana. Below 15 indicates dangerous centralization. Below 10 means a small group can halt consensus."},
    {"metric":"delinquent_validators","normal_range":"0-5","alert_threshold":"> 20","unit":"count","source":"Helius","content":"Delinquent validators: Validators that are not voting. Normal is 0-5 delinquent at any time. Above 20 delinquent suggests coordinated attack or major infrastructure issue. Tracked via getVoteAccounts RPC call."},
    {"metric":"block_time","normal_range":"400-600ms","alert_threshold":"> 2000ms","unit":"milliseconds","source":"Helius","content":"Block time: Solana targets 400ms block time. Normal range 400-600ms. Block times above 1 second indicate network stress. Above 2 seconds indicates serious consensus issues."},
    {"metric":"confirmation_time","normal_range":"0.4-2s","alert_threshold":"> 30s","unit":"seconds","source":"Helius","content":"Transaction confirmation time: Normal confirmed in 0.4-2 seconds. Finalized in ~13 seconds (32 confirmations). Confirmation times above 30 seconds indicate network congestion or validator issues."},
    {"metric":"total_validators","normal_range":"1500-2000","alert_threshold":"< 1000","unit":"count","source":"Validators.app","content":"Total active validators: Solana maintains 1500-2000 active validators. Drops below 1000 indicate mass delinquency or network partition. Healthy validator count contributes to censorship resistance."},
    {"metric":"epoch_duration","normal_range":"2-3 days","alert_threshold":"N/A","unit":"days","source":"Solana Docs","content":"Epoch duration: Each Solana epoch is approximately 432,000 slots (~2-3 days). Stake changes take effect at epoch boundaries. Used for validator rotation and reward distribution."},
    {"metric":"vote_credits_per_epoch","normal_range":"350000-432000","alert_threshold":"< 300000","unit":"credits","source":"Validators.app","content":"Vote credits: Validators earn credits for correct votes. A healthy validator earns close to max credits per epoch. Low credits indicate missed votes, which reduces stake rewards and suggests performance issues."},
    {"metric":"commission_rate","normal_range":"0-10%","alert_threshold":"> 50%","unit":"percentage","source":"Validators.app","content":"Validator commission: Fee taken by validator from delegator rewards. Normal range 0-10%. Validators charging above 50% are exploiting delegators. Default Solana Labs validators charge 100% (all to foundation)."},
    {"metric":"active_stake","normal_range":"350M-450M SOL","alert_threshold":"N/A","unit":"SOL","source":"Validators.app","content":"Active stake: Total SOL staked to active validators. Ranges 350-450M SOL representing ~60-70% of circulating supply. High stake participation increases network security."},
    {"metric":"rpc_response_time","normal_range":"50-200ms","alert_threshold":"> 2000ms","unit":"milliseconds","source":"Helius","content":"RPC response time: Normal RPC calls return in 50-200ms. Above 1 second indicates RPC node overload. Above 2 seconds means the node is severely behind or unreachable. Use multiple endpoints for redundancy."},
]

# ── COLLECTION 5: RESEARCH KNOWLEDGE ────────────────────────
RESEARCH_KNOWLEDGE = [
    {"paper":"FuzzDelSol","arxiv":"2511.11250","year":2024,"concept":"solana_aware_fuzzing","finding":"Stateful sequences find bugs random fuzzing misses","content":"FuzzDelSol research: Coverage-guided fuzzing designed for Solana programs. Key insight: random instruction fuzzing misses stateful bugs. Must fuzz: (1) stateful transaction sequences, (2) account permutations, (3) signer permutations, (4) PDA fuzzing. Implemented in this project as 5-phase fuzzer."},
    {"paper":"FuzzDelSol","arxiv":"2511.11250","year":2024,"concept":"account_permutation_fuzzing","finding":"Passing wrong accounts in each slot finds type cosplay and substitution bugs","content":"FuzzDelSol account permutation technique: Systematically pass wrong account in each instruction slot. Bank as user, user as bank, random account as both. This finds type cosplay, duplicate mutable account, and account substitution vulnerabilities that random fuzzing never reaches."},
    {"paper":"FuzzDelSol","arxiv":"2511.11250","year":2024,"concept":"signer_permutation_fuzzing","finding":"Attacker-signed transactions confirm missing signer/owner check exploitability","content":"FuzzDelSol signer permutation: Send the same transaction signed by an attacker keypair instead of the legitimate owner. If the transaction succeeds, the missing signer or missing owner check is confirmed exploitable, not just detected statically."},
    {"paper":"VRust","arxiv":"2309.03006","year":2023,"concept":"mir_based_static_analysis","finding":"8 vulnerability types detectable via Rust MIR inference rules without code annotations","content":"VRust framework: First automated Solana vulnerability detection via Rust MIR (Mid-level IR). Translates source to MIR and applies inference rules. Found 12 unknown vulnerabilities in 100+ projects including 3 critical in official SPL. Key: MIR-level analysis catches type confusion that source-level analysis misses."},
    {"paper":"VRust","arxiv":"2309.03006","year":2023,"concept":"untrusted_account_validation","finding":"Most critical Solana bugs are missing validation of untrusted input accounts","content":"VRust key finding: The root cause of most Solana vulnerabilities is insufficient validation of accounts passed as instruction inputs. Unlike EVM where callers are authenticated, Solana passes account arrays that programs must validate themselves. The 8 VRust types all relate to this validation gap."},
    {"paper":"Solana Security Analysis","arxiv":"2604.00234","year":2026,"concept":"solana_attack_taxonomy","finding":"Solana-specific attacks differ fundamentally from EVM due to account model","content":"2026 Solana security analysis: Solana's account model creates unique attack surfaces not present in EVM. Key differences: (1) Programs are stateless, data lives in separate accounts, (2) Accounts must be passed explicitly, (3) PDAs replace contract addresses, (4) CPIs replace contract calls. All require different security models."},
    {"paper":"Eclipse Attack","usenix":"sec15-paper-heilman","year":2015,"concept":"p2p_network_eclipse","finding":"Isolating a node from honest peers allows double-spend and 51% attack simulation","content":"Eclipse attack on Bitcoin P2P: Attacker monopolizes all connections to target node, feeding it a false view of the blockchain. Applicable to Solana: isolating validators from gossip network allows feeding false block data. Mitigation: diversify validator connection topology, use multiple RPC endpoints."},
    {"paper":"Solana Outage Analysis","source":"Community Research","year":2023,"concept":"network_congestion_causes","finding":"Solana outages primarily caused by transaction floods not consensus failures","content":"Solana outage pattern analysis: Most Solana outages (2021-2024) were caused by transaction flood overloading validator memory, not consensus bugs. Key vulnerability: no backpressure at transaction ingestion. QUIC implementation mitigated this but congestion events still occur during memecoin/NFT volume spikes."},
    {"paper":"Sandwich Attack Analysis","source":"DeFi Research","year":2023,"concept":"mev_sandwich_attack","finding":"Sandwich attacks on Solana DEXes extract value from large swaps","content":"MEV sandwich attack on Solana: Attacker observes large pending swap, inserts buy before and sell after. On Solana, low transaction fees make smaller sandwiches profitable. Detection: look for [buy, victim_swap, sell] pattern within same slot from same address. Mitigation: slippage protection, private mempools, Jito block engine."},
    {"paper":"Memecoin Ecosystem Study","source":"ResearchGate","year":2024,"concept":"network_stress_from_speculation","finding":"Memecoin speculation creates predictable periodic network stress","content":"Memecoin network stress: pump.fun and similar platforms generate periodic transaction spikes when new tokens launch. Each launch can generate 100k+ transactions in minutes. Causes: failed transactions for non-priority users, validator memory pressure, and Nakamoto coefficient drops as stake concentrates to performant validators."},
    {"paper":"PoH Security","source":"Solana Whitepaper","year":2018,"concept":"proof_of_history_security","finding":"PoH provides verifiable time but not Byzantine fault tolerance alone","content":"Proof of History security properties: PoH is a verifiable delay function that creates a historical record of time. It provides ordering guarantees but requires Tower BFT for Byzantine fault tolerance. Key: PoH allows validators to agree on time without communication, but a 33%+ malicious stake can still halt the network."},
    {"paper":"Helium on Solana","source":"ResearchGate","year":2024,"concept":"iot_oracle_security","finding":"Decentralized IoT networks require physics-based fraud detection","content":"Helium blockchain security: Helium moved to Solana in 2023. IoT hotspot rewards are based on radio coverage proofs. Fraud types: GPS spoofing (false location claims), witness rings (colluding hotspots), signal physics violations (claimed coverage impossible given Friis equation). Requires physics-aware oracle validation."},
]

def main():
    print("Building Unified KB — 5 collections\n")

    col1 = load_collection("sc_rules")
    ingest(col1, SC_RULES, "sc")

    col2 = load_collection("audit_findings")
    ingest(col2, AUDIT_FINDINGS, "af")

    col3 = load_collection("network_incidents")
    ingest(col3, NETWORK_INCIDENTS, "ni")

    col4 = load_collection("validator_baselines")
    ingest(col4, VALIDATOR_BASELINES, "vb")

    col5 = load_collection("research_knowledge")
    ingest(col5, RESEARCH_KNOWLEDGE, "rk")

    print(f"\n✅ Unified KB built")
    print(f"   SC Rules:            {len(SC_RULES)}")
    print(f"   Audit Findings:      {len(AUDIT_FINDINGS)}")
    print(f"   Network Incidents:   {len(NETWORK_INCIDENTS)}")
    print(f"   Validator Baselines: {len(VALIDATOR_BASELINES)}")
    print(f"   Research Knowledge:  {len(RESEARCH_KNOWLEDGE)}")
    print(f"   Total:               {len(SC_RULES)+len(AUDIT_FINDINGS)+len(NETWORK_INCIDENTS)+len(VALIDATOR_BASELINES)+len(RESEARCH_KNOWLEDGE)}")

if __name__ == "__main__":
    main()
